name: my_custom_lints
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter  
  analyzer: ^6.4.1
  analyzer_plugin: ^0.11.3
  custom_lint: ^0.6.4
  custom_lint_builder: ^0.6.4
  build_runner: ^2.4.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter: